variables:
  ECR_REPO_URL: 873799242473.dkr.ecr.ap-northeast-2.amazonaws.com
  #otel-config.yaml
  GRPC_ENDPOINT: "0.0.0.0:4317"
  HTTP_ENDPOINT: "0.0.0.0:4318"
  OTEL_COLLECTOR_VERSION: "0.62.1"
  KIBANA_FLEET_USERNAME: elastic

workflow:
  rules:
  - if: $CI_COMMIT_BRANCH == "develop"
    variables:
        KUBE_CONFIG: ${DEV_KUBE_CONFIG}
        #elastic-agent.yaml
        ELASTIC_AGENT_VERSION: "8.8.1"
        FLEET_URL: "https://a927d56963234c64b8504a1fc0ddafe8.fleet.ap-northeast-2.aws.elastic-cloud.com:443"
        FLEET_ENROLLMENT_TOKEN: "${DEV_FLEET_ENROLLMENT_TOKEN}"
        KIBANA_HOST: "https://dev-arbeon-monitor.kb.ap-northeast-2.aws.elastic-cloud.com:9243"
        #otel-config.yaml
        APM_ENDPOINT: "https://dev-arbeon-monitor.apm.ap-northeast-2.aws.elastic-cloud.com:443"
        APM_SECRET_TOKEN: "${DEV_APM_SECRET_TOKEN}"
        KIBANA_FLEET_PASSWORD: "${DEV_KIBANA_FLEET_PASSWORD}"
        ENV: dev
  - if: $CI_COMMIT_BRANCH == "integration"
    variables:
        KUBE_CONFIG: ${INTE_KUBE_CONFIG}
        #elastic-agent.yaml
        ELASTIC_AGENT_VERSION: "8.8.1"
        FLEET_URL: "https://a927d56963234c64b8504a1fc0ddafe8.fleet.ap-northeast-2.aws.elastic-cloud.com:443"
        FLEET_ENROLLMENT_TOKEN: "${DEV_FLEET_ENROLLMENT_TOKEN}"
        KIBANA_HOST: "https://dev-arbeon-monitor.kb.ap-northeast-2.aws.elastic-cloud.com:9243"
        #otel-config.yaml
        APM_ENDPOINT: "https://dev-arbeon-monitor.apm.ap-northeast-2.aws.elastic-cloud.com:443"
        APM_SECRET_TOKEN: "${DEV_APM_SECRET_TOKEN}"
        KIBANA_FLEET_PASSWORD: "${DEV_KIBANA_FLEET_PASSWORD}"
        ENV: inte
  - if: $CI_COMMIT_BRANCH == "staging"
    variables:
        EKS_CLUSTER_NAME: "arbeon-staging-cls"
        #elastic-agent.yaml
        ELASTIC_AGENT_VERSION: "8.8.1"
        FLEET_URL: "https://a927d56963234c64b8504a1fc0ddafe8.fleet.ap-northeast-2.aws.elastic-cloud.com:443"
        FLEET_ENROLLMENT_TOKEN: "${DEV_FLEET_ENROLLMENT_TOKEN}"
        KIBANA_HOST: "https://dev-arbeon-monitor.kb.ap-northeast-2.aws.elastic-cloud.com:9243"
        #otel-config.yaml
        APM_ENDPOINT: "https://dev-arbeon-monitor.apm.ap-northeast-2.aws.elastic-cloud.com:443"
        APM_SECRET_TOKEN: "${DEV_APM_SECRET_TOKEN}"
        KIBANA_FLEET_PASSWORD: "${DEV_KIBANA_FLEET_PASSWORD}"
        ENV: staging
  - if: $CI_COMMIT_BRANCH == "main"
    variables:
        EKS_CLUSTER_NAME: "arbeon-production-cls"
        #elastic-agent.yaml
        ELASTIC_AGENT_VERSION: "8.8.2"
        FLEET_URL: "https://d5413dfdd9af4b2d9d16ee46b1b0be11.fleet.ap-northeast-2.aws.elastic-cloud.com:443"
        FLEET_ENROLLMENT_TOKEN: "${PROD_FLEET_ENROLLMENT_TOKEN}"
        KIBANA_HOST: "https://prod-arbeon-monitor.kb.ap-northeast-2.aws.elastic-cloud.com:9243"
        #otel-config.yaml
        APM_ENDPOINT: "https://prod-arbeon-monitor.apm.ap-northeast-2.aws.elastic-cloud.com:443"
        APM_SECRET_TOKEN: "${PROD_APM_SECRET_TOKEN}"
        KIBANA_FLEET_PASSWORD: "${PROD_KIBANA_FLEET_PASSWORD}"
        ENV: production
          
stages:
  - deploy

deploy:
  stage: deploy
  image: ${ECR_REPO_URL}/utils/aws-helm:5a7e2aa0
  script:
    - mkdir ${HOME}/.kube
    - base64 --decode ${KUBE_CONFIG} > ${HOME}/.kube/config
    - envsubst < templates/elastic-agent-managed-kubernetes.yaml.template > elastic-agent-managed-kubernetes.yaml
    - envsubst < templates/otel-config.yaml.template > otel-config.yaml
    - cat elastic-agent-managed-kubernetes.yaml
    - cat otel-config.yaml
    - kubectl apply -f elastic-agent-managed-kubernetes.yaml
    - kubectl apply -f otel-config.yaml
  tags:
    - dev
  only:
    - develop
    - integration
  environment:
    name: ${ENV}

    

deploy-eks:
  stage: deploy
  image: ${ECR_REPO_URL}/utils/aws-helm:5a7e2aa0
  script:
    - aws eks update-kubeconfig --region $AWS_REGION --name $EKS_CLUSTER_NAME
    - kubectl get nodes
    - envsubst < templates/elastic-agent-managed-kubernetes.yaml.template > elastic-agent-managed-kubernetes.yaml
    - envsubst < templates/otel-config.yaml.template > otel-config.yaml
    - cat elastic-agent-managed-kubernetes.yaml
    - cat otel-config.yaml
    - kubectl apply -f elastic-agent-managed-kubernetes.yaml
    - kubectl apply -f otel-config.yaml
  tags:
    - aws-runner
  only:
    - main
    - master
    - staging
  environment:
    name: ${ENV}

